apiVersion: v2
name: ext-postgres-operator
description: |
  A Helm chart for the External Postgres operator

  helm upgrade --install -n operators ext-postgres-operator oci://ghcr.io/vterdunov/external-postgres-control-operator/charts/ext-postgres-operator

type: application
version: 3.1.0
appVersion: "2.5.0"
